---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
## Loading required packages

library(tidyverse)
library(dplyr)
library(stringr)
library(readr)
library(readxl)

library(plotly)
library(maps)


library(maps)

new_heart_gender_data=read_csv("data/Heart_Disease_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(state = location_abbr) %>%
  rename(mortality_rate = data_value) %>%
  rename(gender=stratification1)%>%
  rename(race=stratification2)%>%
  mutate(state = state.name[match(state, state.abb)])%>%
  filter(gender%in%c("Male","Female"))%>%
  filter(race=="Overall")%>%
  select(state,location_desc, mortality_rate,gender)

new_stroke_gender_data=read_csv("data/Stroke_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(state = location_abbr) %>%
  rename(stroke_value = data_value) %>%
  rename(gender=stratification1)%>%
  rename(race=stratification2)%>%
  mutate(state = state.name[match(state, state.abb)])%>%
  filter(gender%in%c("Male","Female"))%>%
  filter(race=="Overall")%>%
  select(state, location_desc, stroke_value,gender)
new_gender_data=left_join(new_heart_gender_data,new_stroke_gender_data)%>%
  filter(!is.na(stroke_value))


  

new_heart_race_data=read_csv("data/Heart_Disease_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(state = location_abbr) %>%
  rename(mortality_rate = data_value) %>%
  rename(gender=stratification1)%>%
  rename(race=stratification2)%>%
  mutate(state = state.name[match(state, state.abb)])%>%
  filter(gender=="Overall")%>%
  filter(!(race=="Overall"))%>%
  select(state, location_desc, mortality_rate, race)

new_stroke_race_data=read_csv("data/Stroke_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(state = location_abbr) %>%
  rename(stroke_value = data_value) %>%
  rename(gender=stratification1)%>%
  rename(race=stratification2)%>%
  mutate(state = state.name[match(state, state.abb)])%>%
  filter(gender=="Overall")%>%
  filter(!(race=="Overall"))%>%
  select(state, location_desc, stroke_value,race)
new_race_data=left_join(new_heart_race_data,new_stroke_race_data)%>%
  filter(!is.na(stroke_value))




```

```{r input_heart_disease_data}
heart_disease_stratify =  read_csv("data/Heart_Disease_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(state = location_abbr) %>%
  rename(mortality_rate = data_value) %>%

  mutate(state = state.name[match(state, state.abb)]) %>% 
  select(-data_source, -geographic_level, -class, -topic, -data_value_footnote, -data_value_footnote_symbol, -topic_id, -location_id ) 

heart_disease = heart_disease_stratify %>% 
  filter(stratification1 == "Overall", stratification2 == "Overall") %>% 
  select(-stratification1, -stratification2, -stratification_category1, -stratification_category2) 

heart_disease$mortality_rate[is.na(heart_disease$mortality_rate)] = 0

heart_disease = 
heart_disease %>% 
  group_by(state) %>% 
  summarise(mortality_rate = mean(mortality_rate))
  
  
```

Add air quality data 

```{r}
airquality_2015 = read_csv("data/airquality.csv") %>%
  janitor::clean_names() %>%
  select(state, pm2_5) %>% 
  group_by(state) %>% 
  summarize(pm2.5 = sum(pm2_5))

```

Add obesity data

```{r add_obesity_data}
obesity_data = read_csv("data/National_Obesity_By_State.csv") %>%
  janitor::clean_names() %>%
  rename(state = name) %>%
  rename(obesity_percentage = obesity) %>%
  select(state, obesity_percentage) 
data_with_obesity = left_join(heart_disease, obesity_data)
```

Add stroke data

```{r add_stroke_data}
stroke_data = read_csv("data/Stroke_Mortality_Data_Among_US_Adults__35___by_State_Territory_and_County.csv") %>%
  janitor::clean_names() %>%
  rename(stroke_value=data_value)%>%
  rename(state = location_abbr) %>%
  mutate(state = state.name[match(state, state.abb)])%>%

  select(state,stroke_value) %>% 
  group_by(state) %>% 
  filter(!is.na(stroke_value)) %>% 
  summarize(stroke_value = sum(stroke_value)) 
```



Add income

```{r}
income_data = read_excel("data/income_2015.xlsx", range = "A4:D55") %>%
  janitor::clean_names() %>%
  rename(state = united_states, median_income = x55117, income_standard_error = x253) 
data_with_income = left_join(heart_disease,income_data, by = "state")
```




```{r}
data_income_obesity = left_join(income_data,data_with_obesity, by = "state")


smoking_data = read_csv("data/smoking.csv") %>% 
  filter(YEAR == "2015-2016") %>% 
  mutate(year = 2015) %>% 
  rename(state = LocationDesc) %>% 
  select(-YEAR) %>% 

  select(year, state, Data_Value) %>% 

  select(year, state, Data_Value) %>% 
  rename(tobacco_comsumption = Data_Value) %>% 
  group_by(state) %>% 
  summarise(tobacco_consumption = sum(tobacco_comsumption))


data_income_obesity_smoking = left_join(smoking_data, data_income_obesity, by = "state")

data_income_obesity_smoking_air = left_join(airquality_2015, data_income_obesity_smoking, by = "state")




data_income_obesity_smoking = left_join(smoking_data, data_income_obesity, by = "state")
data_income_obesity_smoking_air = left_join(airquality_2015, data_income_obesity_smoking, by = "state")


final_data = left_join(stroke_data, data_income_obesity_smoking_air, by = "state") 



  

```

Column {data-width=650}
-----------------------------------------------------------------------

### Aisle v.s. Order Number

```{r}
final_data %>% 
  lm(mortality_rate ~ median_income + pm2.5 + obesity_percentage + stroke_value + tobacco_consumption, data = .)


  
```



Column {data-width=350}
-----------------------------------------------------------------------

### Interval between Orders for Each Aisle

```{r}
gender_stroke = ggplot(new_gender_data,aes(x=mortality_rate,y=stroke_value))+
  geom_point(aes(color=gender), alpha = .5)

ggplotly(gender_stroke)

```

### Order Hour For Different Department

```{r}
race_stroke = ggplot(new_race_data, aes(x=mortality_rate,y=stroke_value))+
  geom_point(aes(color=race))

ggplotly(race_stroke)

```

