<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Report</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Report.html">Report</a>
</li>
<li>
  <a href="mlr_analysis.html">MLR Analysis</a>
</li>
<li>
  <a href="dashboard_template.html">FlexDashboard</a>
</li>
<li>
  <a href="https://sy2825.shinyapps.io/p8105_final_project">Fantastic Shiny</a>
</li>
<li>
  <a href="mailto:&lt;jw3726@columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/qinyao2282/P8105_final_project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Report</h1>
<h4 class="date"><em>2018/12/3</em></h4>

</div>


<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.8
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(dplyr)
library(stringr)
library(readr)
library(readxl)

library(plotly)</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<pre class="r"><code>library(maps)</code></pre>
<pre><code>## 
## Attaching package: &#39;maps&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     map</code></pre>
<pre class="r"><code>library(gsheet)</code></pre>
<p>Group project report</p>
<p>Member: Haowei Ni, Qinyao Wu, Jiabei Wang, Shuo Yan, Bihui Sun</p>
<div id="motivation" class="section level2">
<h2>• Motivation:</h2>
<p>The goal of this project is to analysis the factor that might contribute to the mortality rate of heart disease both demographically and geographically. The motivation is that as a public health student, it is our responsibility to learn about the diseases that keep threatening our lives and take early action for prevention. We believe that explore the factors that might related to the mortality rate of heart disease might be the next step that people take to assess possible treatment options.</p>
</div>
<div id="related-work" class="section level2">
<h2>• Related work:</h2>
<p>Heart disease is the leading cause of death for both men and women. About 610,000 people die of heart disease in the United States every year–that’s 1 in every 4 deaths. It is also the leading cause of death in most ethnicities groups, including white, African American, Asian and Hispanic.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>• Initial questions:</h2>
<p>What was the geographic distribution of mortality rate? Does the mortality rate has difference between the state that are in coastal area or inland area? Does the rate affect by the longitude or latitude? Which ethnic group has the highest morality rate? Does men have higher mortality rate than women? Are there any interactions between these two factors. After adding other variables that might affect the mortality rate, we came up with a new question. Can we make a logistic model for heart disease mortality rate based on the variables that have significant correlation?</p>
</div>
<div id="data" class="section level2">
<h2>• Data:</h2>
<p>The data were obtained when searching for the key world “heart disease mortality rate” on the website <a href="https://www.data.gov/" class="uri">https://www.data.gov/</a> This website is an open data source in US that covered various topics including “Health”, which we take most interest in. Data was updated on August 20, 2018 that describes heart disease mortality rate among US adults (35+) by state and county.</p>
<p>First we download the original dataset we download from data.gov and stored in our google sheet.</p>
<pre class="r"><code>heart_disease_stratify = gsheet2tbl(&#39;docs.google.com/spreadsheets/d/1W-xVHLoeZj37wrZdX-dP_SVouZKg5VmTpFdmOLWByR4/edit?usp=sharing&#39;) %&gt;%

  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(mortality_rate = data_value) %&gt;%

  mutate(state = state.name[match(state, state.abb)]) %&gt;% 
  select(-data_source, -geographic_level, -class, -topic, -data_value_footnote, -data_value_footnote_symbol, -topic_id, -location_id ) 

heart_disease = heart_disease_stratify %&gt;% 
  filter(stratification1 == &quot;Overall&quot;, stratification2 == &quot;Overall&quot;) %&gt;% 
  select(-stratification1, -stratification2, -stratification_category1, -stratification_category2) </code></pre>
<p>Then we tidied the data set by grouping with states.</p>
<pre class="r"><code>heart_disease$mortality_rate[is.na(heart_disease$mortality_rate)] = 0

heart_disease = 
heart_disease %&gt;% 
  group_by(state) %&gt;% 
  summarise(mortality_rate = mean(mortality_rate))</code></pre>
<p>Then we add more variables from additional resources.</p>
<p>•1. Add air quality data and tidy the dataset.</p>
<pre class="r"><code>airquality_2015 =
  gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1CRJzMI0QbqU34BZZQ1bg3BnZPM_oUfVUCVPOo4AnoB0/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  select(state, pm2_5) %&gt;%   
  group_by(state) %&gt;% 
  summarize(pm2.5 = sum(pm2_5))</code></pre>
<p>•2. Add obesity data and tidy the dataset.</p>
<pre class="r"><code>obesity_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1zlB2cOOMvD-IJIiGQ6YOyQ6QEXEKVAkrPTzxZrYci28/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = name) %&gt;%
  rename(obesity_percentage = obesity) %&gt;%
  select(state, obesity_percentage) 
data_with_obesity = left_join(heart_disease, obesity_data)</code></pre>
<pre><code>## Joining, by = &quot;state&quot;</code></pre>
<p>•3. Add stroke data and tidy the dataset.</p>
<pre class="r"><code>stroke_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1AZkDl8sNrTDnEX3Fhp1MeWNKNj9rnXaKaMbpVGndv5s/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(stroke_value=data_value)%&gt;%
  rename(state = location_abbr) %&gt;%
  mutate(state = state.name[match(state, state.abb)])%&gt;%

  select(state,stroke_value) %&gt;% 
  group_by(state) %&gt;% 
  filter(!is.na(stroke_value)) %&gt;% 
  summarize(stroke_value = sum(stroke_value)) </code></pre>
<p>•4. Add income data and tidy the dataset.</p>
<pre class="r"><code>income_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1_Rd_dxRgMqOCaFC-8fWz6QODG8_IBZl1DnQOFaRxF0Q/edit?usp=sharing&#39;) %&gt;% 
  rename(state = &quot;X1&quot;, us = &quot;X2&quot;, median_income = &quot;X3&quot;, income_standard_error = &quot;X4&quot; )</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1], &#39;X2&#39; [2], &#39;X3&#39; [3],
## &#39;X4&#39; [4]</code></pre>
<pre class="r"><code>income_data = income_data[3:53,]


data_with_income = left_join(heart_disease,income_data, by = &quot;state&quot;)

data_income_obesity = left_join(income_data,data_with_obesity, by = &quot;state&quot;)</code></pre>
<p>•5. Add smoking data and tidy the dataset.</p>
<pre class="r"><code>smoking_data = gsheet2tbl(&quot;https://docs.google.com/spreadsheets/d/1ZU7uuqV-EZM81hE4kq0nFiPJHUMJj82fnXVllGFHJ00/edit?usp=sharing&quot;) %&gt;% 
  filter(YEAR == &quot;2015-2016&quot;) %&gt;% 

  mutate(year = 2015) %&gt;% 
  rename(state = LocationDesc) %&gt;% 
  select(-YEAR) %&gt;%
  filter(!is.na(Data_Value)) %&gt;%

  select(year, state, Data_Value) %&gt;% 

  select(year, state, Data_Value) %&gt;% 
  rename(tobacco_comsumption = Data_Value) %&gt;% 
  group_by(state) %&gt;% 
  summarise(tobacco_consumption = sum(tobacco_comsumption))</code></pre>
<p>Then we combine all the data with the original data set to generate our final data.</p>
<pre class="r"><code>data_income_obesity_smoking = left_join(smoking_data, data_income_obesity, by = &quot;state&quot;)

data_income_obesity_smoking_air = left_join(airquality_2015, data_income_obesity_smoking, by = &quot;state&quot;)




data_income_obesity_smoking = left_join(smoking_data, data_income_obesity, by = &quot;state&quot;)
data_income_obesity_smoking_air = left_join(airquality_2015, data_income_obesity_smoking, by = &quot;state&quot;)</code></pre>
<p>Here is our final data.</p>
<pre class="r"><code>final_data_export = left_join(stroke_data, data_income_obesity_smoking_air, by = &quot;state&quot;) 

final_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1ifmyU22AaB81PvMDCCRrsIqtifa0FuKhH5MpI_FU0Sc/edit?usp=sharing&#39;)</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
</div>
<div id="scrape-and-clean" class="section level2">
<h2>• Scrape and Clean:</h2>
<p>There are total 59076 rows and 19 variables in the original dataset. It describes the mortality rate across each county in year 2015. First, we removed 8 columns that basically give no useful information for analysis such as “data_source”, “class”, “topic”, “stratification1”, etc. Second, since we are looking for a more general result in a larger geographically scale, we create a new dataset that calculate the total and summarize the mean mortality rate in each state called “heart_disease.csv”. Then we added 5 other variables that might affect the mortality rate. For air quality and tobacco consumption, we take the sum value for each state. For obesity and stroke data, we take the mean percentage for each state. For income, we take the median for each state. Then we create a new dataset called “final_data.csv” by joining the new variables with the mortality rate across each state.</p>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>• Exploratory analysis:</h2>
<p>For each variable, we make a scatterplot that can compare the mortality rate trend with the corresponding variable across each state. Then we make a simple linear regression to determine whether the variable has significant correlation with the mortality rate.</p>
<div id="air-quality" class="section level4">
<h4>1. Air quality</h4>
<pre class="r"><code>final_data %&gt;% 
  mutate(state = fct_reorder(state, mortality_rate)) %&gt;% 
  ggplot(aes(x = mortality_rate, y = pm2.5, color = state)) + 
  geom_point() +
  ggtitle(&quot;Airquality VS Mortality Rate &quot;) +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  theme(legend.position = &quot;bottom&quot;,
        legend.direction = &quot;horizontal&quot;,
        axis.text.x = element_text(angle = 90, size = 6),
        legend.key.size = unit(0.05, &quot;cm&quot;)) + 
  labs(x = &quot;Mortality Rate&quot;,
       y = &quot;PM2.5&quot;) </code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>## fit simple linear regression model 
lm(final_data$mortality_rate~final_data$pm2.5) %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">338.1788076</td>
<td align="right">14.2703341</td>
<td align="right">23.6980302</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">final_data$pm2.5</td>
<td align="right">0.0009734</td>
<td align="right">0.0046731</td>
<td align="right">0.2083025</td>
<td align="right">0.8358741</td>
</tr>
</tbody>
</table>
<p>From the scatterplot, we can see that the points are spread randomly. However, the relationship between pm2.5 and mortality rate is unclear. For the states, with low pm2.5, some of them have low mortality rate and some of them have high mortality rate. After we fit the simple regression model, the p-value for pm2.5 is 0.836, so it is a non-significant variable.</p>
</div>
<div id="stroke" class="section level4">
<h4>2. Stroke</h4>
<pre class="r"><code>mydata1=heart_disease_stratify %&gt;%
  filter(stratification1 == &quot;Overall&quot;, stratification2 == &quot;Overall&quot;) %&gt;%
  select(state, location_desc, mortality_rate) %&gt;%
  filter(!is.na(mortality_rate))
  
mydata2 = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1AZkDl8sNrTDnEX3Fhp1MeWNKNj9rnXaKaMbpVGndv5s/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(stroke_value = data_value) %&gt;%
  mutate(state = state.name[match(state, state.abb)]) %&gt;%
  filter(stratification1 == &quot;Overall&quot;, stratification2 == &quot;Overall&quot;) %&gt;%
  select(state, location_desc, stroke_value) %&gt;%
  filter(!is.na(stroke_value))
                                                                                                                    
comdata = left_join(mydata1,mydata2)  </code></pre>
<pre><code>## Joining, by = c(&quot;state&quot;, &quot;location_desc&quot;)</code></pre>
<pre class="r"><code>final_data %&gt;%
  mutate(state = forcats::fct_reorder(state,stroke_value)) %&gt;%
  ggplot(aes(x = mortality_rate, y = stroke_value)) + 
  geom_point(aes(color = state), alpha = .5)</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>comdata %&gt;%
  mutate(state = forcats::fct_reorder(state,stroke_value)) %&gt;%
  ggplot(aes(x = mortality_rate, y = stroke_value)) + 
  geom_point(aes(color = state), alpha = .5)</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>lm(mortality_rate~stroke_value,data = comdata) %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">143.236305</td>
<td align="right">5.9886300</td>
<td align="right">23.91804</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">stroke_value</td>
<td align="right">2.746495</td>
<td align="right">0.0752517</td>
<td align="right">36.49744</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>From the linear regression, we find that p-value is less than 2e-16, indicates there is very significant association between stroke and heart disease mortality. From the plot, we can see that with higher stroke value, the heart disease mortality rate goes higher.</p>
</div>
<div id="income" class="section level4">
<h4>3. Income</h4>
<pre class="r"><code>final_data_income = 
  final_data %&gt;% 
  mutate(state = forcats::fct_reorder(factor(state), median_income)) 

final_data_income %&gt;% 
  ggplot(aes(x = mortality_rate, y = median_income, color = state)) +
  geom_point() +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  theme(text = element_text(size = 8), axis.text.x = element_text(angle = 60, hjust = 1), legend.position = &quot;bottom&quot;) + 

  #Add the title and the name for x and y axis. 
  labs(
    title = &quot;Association between Income and Heart Disease Mortality Rate&quot;,
    x = &quot;Mortality Rate&quot;,
    y = &quot;median_income&quot;
  )</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>lm(mortality_rate ~ median_income, data = final_data_income) %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">610.2373902</td>
<td align="right">39.9405637</td>
<td align="right">15.278637</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">median_income</td>
<td align="right">-0.0048261</td>
<td align="right">0.0007058</td>
<td align="right">-6.838044</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>From the plot, the fitted line is downward implying that the state with highst median income tend to have the lowest mortality rate. From the lm result, we can observe that median_income is a very significant variable with a p value of 1.3e-08. This indicates there is a strong association between income and heart disease mortality rate.</p>
</div>
<div id="tabacco-consumption" class="section level4">
<h4>4 Tabacco consumption</h4>
<pre class="r"><code> final_data %&gt;%
  mutate(state = forcats::fct_reorder(factor(state), tobacco_consumption)) %&gt;%
  ggplot(aes(x = mortality_rate, y = tobacco_consumption)) + 
  geom_point(aes(color = state), alpha = .5) +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  labs(
    title = &quot;Tabacco Consumption Accross states&quot;
  ) +
  theme(text = element_text(size = 8), axis.text = element_text(angle = 60, hjust = 1), legend.position = &quot;bottom&quot;)</code></pre>
<pre><code>## Warning: Removed 14 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 14 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>lm(mortality_rate~tobacco_consumption, data = final_data) %&gt;%
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">241.8405899</td>
<td align="right">45.2029014</td>
<td align="right">5.350112</td>
<td align="right">0.0000056</td>
</tr>
<tr class="even">
<td align="left">tobacco_consumption</td>
<td align="right">0.8384022</td>
<td align="right">0.3669033</td>
<td align="right">2.285077</td>
<td align="right">0.0284808</td>
</tr>
</tbody>
</table>
<p>From the plot, the fitted line fails to catch most of the points and points are spread randomly, so at this point we cannot make any conclusion. From the simple linear regression model, the p-value is 0.028 &lt; 0.05, indicating that there is strong correlation between tabacco comsumption and heart disease.</p>
</div>
<div id="obesity" class="section level4">
<h4>5. Obesity</h4>
<pre class="r"><code>final_data %&gt;%
  ggplot(aes(x = obesity_percentage, y = mortality_rate)) + 
  geom_point(aes(color = state), alpha = .5) +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  labs(
    x = &quot;Obesity(%)&quot;,
    y = &quot;Mortality&quot;,
    title = &quot;Heart Disease Mortality vs Obesity&quot;
  ) +
  theme(text = element_text(size = 8), 
        axis.text = element_text(angle = 60, hjust = 1), 
        legend.position = &quot;bottom&quot;,
        plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>  lm(mortality_rate ~ obesity_percentage, data = final_data) %&gt;%
    broom::tidy() %&gt;% 
    knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-17.78153</td>
<td align="right">46.853534</td>
<td align="right">-0.3795132</td>
<td align="right">0.7059807</td>
</tr>
<tr class="even">
<td align="left">obesity_percentage</td>
<td align="right">12.17623</td>
<td align="right">1.579593</td>
<td align="right">7.7084604</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<p>From the plot, the fitted line is upward indicating that as the obesity percentage goes higher, the mortality rate would increase correspondingly.</p>
</div>
</div>
<div id="additional-analysis" class="section level2">
<h2>• Additional analysis:</h2>
<p>Because gender and race are categorical variable, so we want to measure the interaction between these two. Gender and race will affect the relationship between stroke and mortality rate.</p>
<div id="gender-v.s.-stroke" class="section level4">
<h4>1. Gender v.s. Stroke</h4>
<pre class="r"><code>new_heart_gender_data = gsheet2tbl(&#39;docs.google.com/spreadsheets/d/1W-xVHLoeZj37wrZdX-dP_SVouZKg5VmTpFdmOLWByR4/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(mortality_rate = data_value) %&gt;%
  rename(gender = stratification1) %&gt;%
  rename(race =  stratification2) %&gt;%
  mutate(state = state.name[match(state, state.abb)]) %&gt;%
  filter(gender %in% c(&quot;Male&quot;,&quot;Female&quot;)) %&gt;%
  filter(race == &quot;Overall&quot;) %&gt;%
  select(state,location_desc, mortality_rate,gender)

new_stroke_gender_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1AZkDl8sNrTDnEX3Fhp1MeWNKNj9rnXaKaMbpVGndv5s/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(stroke_value = data_value) %&gt;%
  rename(gender = stratification1) %&gt;%
  rename(race = stratification2) %&gt;%
  mutate(state = state.name[match(state, state.abb)]) %&gt;%
  filter(gender %in% c(&quot;Male&quot;,&quot;Female&quot;)) %&gt;%
  filter(race == &quot;Overall&quot;) %&gt;%
  select(state, location_desc, stroke_value,gender)
new_gender_data = left_join(new_heart_gender_data,new_stroke_gender_data) %&gt;%
  filter(!is.na(stroke_value))</code></pre>
<pre><code>## Joining, by = c(&quot;state&quot;, &quot;location_desc&quot;, &quot;gender&quot;)</code></pre>
<pre class="r"><code>lm(mortality_rate~stroke_value+gender+stroke_value*gender,data = new_gender_data) %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">112.4951619</td>
<td align="right">6.2709892</td>
<td align="right">17.938982</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">stroke_value</td>
<td align="right">2.2135119</td>
<td align="right">0.0802790</td>
<td align="right">27.572728</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">genderMale</td>
<td align="right">111.9970676</td>
<td align="right">8.5616732</td>
<td align="right">13.081213</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">stroke_value:genderMale</td>
<td align="right">0.6111176</td>
<td align="right">0.1080245</td>
<td align="right">5.657213</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<pre class="r"><code>ggplot(new_gender_data,aes(x = mortality_rate,y = stroke_value)) +
  geom_point(aes(color = gender), alpha = .5)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="race-v.s.-stroke" class="section level4">
<h4>2. Race v.s. Stroke</h4>
<pre class="r"><code>new_heart_race_data = gsheet2tbl(&#39;docs.google.com/spreadsheets/d/1W-xVHLoeZj37wrZdX-dP_SVouZKg5VmTpFdmOLWByR4/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(mortality_rate = data_value) %&gt;%
  rename(gender = stratification1) %&gt;%
  rename(race = stratification2) %&gt;%
  mutate(state = state.name[match(state, state.abb)]) %&gt;%
  filter(gender == &quot;Overall&quot;) %&gt;%
  filter(!(race == &quot;Overall&quot;)) %&gt;%
  select(state, location_desc, mortality_rate, race)

new_stroke_race_data = gsheet2tbl(&#39;https://docs.google.com/spreadsheets/d/1AZkDl8sNrTDnEX3Fhp1MeWNKNj9rnXaKaMbpVGndv5s/edit?usp=sharing&#39;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(state = location_abbr) %&gt;%
  rename(stroke_value = data_value) %&gt;%
  rename(gender = stratification1) %&gt;%
  rename(race = stratification2) %&gt;%
  mutate(state = state.name[match(state, state.abb)]) %&gt;%
  filter(gender == &quot;Overall&quot;) %&gt;%
  filter(!(race == &quot;Overall&quot;)) %&gt;%
  select(state, location_desc, stroke_value,race)
new_race_data=left_join(new_heart_race_data,new_stroke_race_data) %&gt;%
  filter(!is.na(stroke_value))</code></pre>
<pre><code>## Joining, by = c(&quot;state&quot;, &quot;location_desc&quot;, &quot;race&quot;)</code></pre>
<pre class="r"><code>lm(mortality_rate~stroke_value + race+stroke_value*race,data = new_race_data) %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">175.9393665</td>
<td align="right">13.1181188</td>
<td align="right">13.411936</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">stroke_value</td>
<td align="right">2.5702619</td>
<td align="right">0.1565890</td>
<td align="right">16.414068</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">raceAsian and Pacific Islander</td>
<td align="right">-50.8486724</td>
<td align="right">15.7665904</td>
<td align="right">-3.225090</td>
<td align="right">0.0012654</td>
</tr>
<tr class="even">
<td align="left">raceBlack</td>
<td align="right">95.0940582</td>
<td align="right">15.3999780</td>
<td align="right">6.174948</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">raceHispanic</td>
<td align="right">-62.8308630</td>
<td align="right">14.8477653</td>
<td align="right">-4.231671</td>
<td align="right">0.0000235</td>
</tr>
<tr class="even">
<td align="left">raceWhite</td>
<td align="right">-23.2945875</td>
<td align="right">15.0277563</td>
<td align="right">-1.550104</td>
<td align="right">0.1211640</td>
</tr>
<tr class="odd">
<td align="left">stroke_value:raceAsian and Pacific Islander</td>
<td align="right">-2.0686943</td>
<td align="right">0.2011428</td>
<td align="right">-10.284707</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">stroke_value:raceBlack</td>
<td align="right">-1.1864310</td>
<td align="right">0.1721524</td>
<td align="right">-6.891749</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">stroke_value:raceHispanic</td>
<td align="right">-1.1270795</td>
<td align="right">0.1901087</td>
<td align="right">-5.928605</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">stroke_value:raceWhite</td>
<td align="right">0.1905714</td>
<td align="right">0.1830054</td>
<td align="right">1.041343</td>
<td align="right">0.2977540</td>
</tr>
</tbody>
</table>
<pre class="r"><code>ggplot(new_race_data, aes(x = mortality_rate,y=stroke_value))+
  geom_point(aes(color = race))</code></pre>
<pre><code>## Warning: Removed 13 rows containing missing values (geom_point).</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="mlr" class="section level4">
<h4>3. MLR</h4>
<p>Further more, we make a multi linear regression model that only include the significant variable that we discussed above.</p>
<pre class="r"><code>final_data = final_data %&gt;%
  janitor::clean_names()

lm(mortality_rate ~ tobacco_consumption + median_income + obesity_percentage + pm2_5 + stroke_value, data = final_data) %&gt;%
    broom::tidy() %&gt;% 
    knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">265.6040888</td>
<td align="right">111.0485303</td>
<td align="right">2.391784</td>
<td align="right">0.0230185</td>
</tr>
<tr class="even">
<td align="left">tobacco_consumption</td>
<td align="right">-0.1949951</td>
<td align="right">0.3276359</td>
<td align="right">-0.595158</td>
<td align="right">0.5560579</td>
</tr>
<tr class="odd">
<td align="left">median_income</td>
<td align="right">-0.0027163</td>
<td align="right">0.0009789</td>
<td align="right">-2.774957</td>
<td align="right">0.0092715</td>
</tr>
<tr class="even">
<td align="left">obesity_percentage</td>
<td align="right">8.4198965</td>
<td align="right">3.0039346</td>
<td align="right">2.802956</td>
<td align="right">0.0086549</td>
</tr>
<tr class="odd">
<td align="left">pm2_5</td>
<td align="right">-0.0040359</td>
<td align="right">0.0039113</td>
<td align="right">-1.031861</td>
<td align="right">0.3101209</td>
</tr>
<tr class="even">
<td align="left">stroke_value</td>
<td align="right">0.0003026</td>
<td align="right">0.0002155</td>
<td align="right">1.403914</td>
<td align="right">0.1702838</td>
</tr>
</tbody>
</table>
<pre class="r"><code>total_lm = lm(mortality_rate ~ tobacco_consumption + median_income + obesity_percentage + pm2_5 + stroke_value, data = final_data) %&gt;%
  fortify()


ggplot(total_lm, aes(x = .fitted, y = .resid)) + geom_point() + 
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  labs(
    x = &quot;Fitted value&quot;,
    y = &quot;Residual&quot;,
    title = &quot;Residuals vs Fitted&quot;
  ) +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The linear model is heart disease mortality = 266 + -0.0027 x median income + 8.4 x obesity percentage. This result indicates that Obesity level contributes a lot to the occurence of heart disease mortality.</p>
</div>
</div>
<div id="discussion" class="section level2">
<h2>• Discussion:</h2>
<p>We found that obesity and income level has huge contribution to the heart-disease mortality rate. There is negative relationship between income level and mortality rate. And postive relationship between obesity percentage and mortality rate. However, smoking status, airquality and stroke don’t have linear relationship with heart disease mortality rate. It is unexpected because we think poor airquality and heavy smoking would increase the mortality rate. In the further analysis, we can try non-linear models.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
