---

title: "Shiny Dashboard"

output: 

  flexdashboard::flex_dashboard:

    orientation: columns

    vertical_layout: fill

runtime: shiny

---



```{r setup, include=FALSE}

library(flexdashboard)

library(tidyverse)

library(viridis)

library(plotly)

```


```{r import_data}
final_data = read_csv("./data/final_data.csv")

variable = list("obesity_percentage", "stroke_value", "pm2.5", "tobacco_consumption", "median_income")

map_variable = list("mortality_rate", "obesity_percentage", "stroke_value", "pm2.5", "tobacco_consumption", "median_income")
```



Column {.sidebar}

-----------------------------------------------------------------------



```{r selectinput}


selectInput("variable_choice", label = h3("Select plot variable"),

            choices = variable, selected = "obesity_percentage")

selectInput("map_choice", label = h3("Select map variable"),

            choices = map_variable, selected = "mortality_rate")

```

Column {data-width=650}
-----------------------------------------------------------------------



### Variable distribution



```{r variable_distriution}

renderPlotly({ 
  
  variable_name = input$variable_choice
  
  plot_data = final_data %>%
    select(variable_name, mortality_rate)
  
  colnames(plot_data) = c("variable_value", "mortality_rate")
  
  plot_data = plot_data %>%
     mutate(text_label = str_c(variable_name, ": ", variable_value, '\nMortality rate: ', mortality_rate)) %>%
    filter(!is.na(variable_value)) %>%
    filter(!is.na(mortality_rate))
  
  fit = lm(mortality_rate ~ variable_value, data = plot_data)
  
  plot_data %>%
  plot_ly(x = ~variable_value, y = ~mortality_rate, type = "scatter", mode = "markers",
          alpha = 0.5,
          text = ~text_label) %>%
    layout(xaxis = list(title = variable_name),
           yaxis = list(title = "Mortality Rate"),
           showlegend = F) %>%
    add_lines(x = ~variable_value, y = fitted(fit))
})

```




Column {data-width=350}

-----------------------------------------------------------------------

### Map

```{r map}

renderPlotly({

  
  map_variable_name = input$map_choice
  
map_data = final_data %>%
  select(map_variable_name, state, us) %>%
  mutate(state = tolower(state)) 

colnames(map_data) = c("variable_value", "state", "us")


states <- map_data("state") %>% 
  rename(state = region)
  
a = left_join(states, map_data, by = "state") %>% 
  mutate(text_label = str_c("Region: ", state, map_variable_name, variable_value) ) 

a$text_label <- with(a, paste(state, '<br>', map_variable_name, variable_value))
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

p <- plot_geo(a, locationmode = 'USA-states') %>%
  add_trace(
    z = ~variable_value, text = ~text_label, locations = ~us,
    color = ~variable_value, colors = 'Purples'
  ) %>%
  colorbar(title = map_variable_name) %>%
  layout(
    title = "Information about the selected map varible for each state",
    geo = g
  )
p
  
})


```

